# Config format schema number
format_version: 4

vanilla_model_name: 'STF_the_world'
vanilla_ckpt: 'STF_the_world_10'
oracle_model_name: 'STF_king_crimson'
oracle_ckpt: 'STF_king_crimson_crash_9'
track: 'motion'

# dataset related
dataset_cfg:
  cache: False
  cache_name: cache2
  shrink: False
  dataset_dir: '/data/uncompressed/trans_val'
  # dataset_dir: '/mnt/lustre/share/zhangqihang/WOD/trans'
  shuffle: True
  batch_size: 4
  num_workers: 1

# model related
vanilla_model_cfg:
  #vector net related
  lane_dims: 11
  traj_dims: 7
  out_dims: 160
  subgraph_width_unit: 32
  num_subgraph_layers: 2
  prop_num: 6
  d_model: 128
  attention_head: 2
  dropout: 0.0
  model_layers_num: 2
  max_pred_num: 8

# model related
oracle_model_cfg:
  #vector net related
  lane_dims: 11
  traj_dims: 4
  out_dims: 160
  subgraph_width_unit: 32
  num_subgraph_layers: 2
  prop_num: 6
  d_model: 128
  attention_head: 2
  dropout: 0.0
  model_layers_num: 2
  max_pred_num: 8

# training related
train_cfg:
  lr: 0.0003
  weight_decay: 0.0004
  lr_decay_per_epoch: 15
  decay_rate: 0.2
  max_norm_gradient: 0.1

eval_cfg:
  shuffle: False
  batch_size: 8
  num_workers: 2

# loss related
loss_cfg:
  K: 100
