# Config format schema number
format_version: 4

model_name: 'STF_the_world'
track: 'motion'

# dataset related
dataset_cfg:
  cache: False
  cache_name: 'cache10'
  shrink: False
  dataset_dir: '/data/uncompressed/trans_val'
  #dataset_dir: '/home/SENSETIME/fenglan/waymo-challenge/trans'
  shuffle: True
  batch_size: 8
  num_workers: 0

# model related
model_cfg:
  #vector net related
  lane_dims: 11
  traj_dims: 7
  out_dims: 160
  subgraph_width_unit: 32
  num_subgraph_layers: 2
  enc_dims:

  prop_num: 6
  d_model: 128
  attention_head: 2
  dropout: 0.0
  model_layers_num: 2
  max_pred_num: 8

# training related
train_cfg:
  lr: 0.0003
  weight_decay: 0.0004
  lr_decay_per_epoch: 15
  decay_rate: 0.2
  max_norm_gradient: 0.1

eval_cfg:
  shuffle: False
  batch_size: 8
  num_workers: 2

# loss related
loss_cfg:
  K: 100
